spring:
  zipkin:
    base-url: http://zipkin-service:9411/
  rabbitmq:
    username: guest
    password: guest
    host: rabbit-service
    port: 5672
eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
    instance:
      hostname: eureka-server
management:
  health:
    circuitbreakers:
      enabled: true
  info:
    env:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health,info,circuitbreakers,circuitbreakerevents
  endpoint:
    health:
      show-details: always
info:
  author: Camila Ferreira
  mail: cftinelli@outlook.com
server:
  port: ${PORT:9999}
message: Mensagem generica

## Resilience4J configs for CircuitBreaker Pattern
resilience4j:
  circuitbreaker:
    instances:
      movie-service:
        allowHealthIndicatorToFail: false
        registerHealthIndicator: true
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 5
        failueRateThreshold: 50
        waitDurationInOpenState: 50s
        permittedNumberOfCalssInHalfOpenState: 2
        automaticTransitionFromOpenToHalfIfOpenEnabled: true

retry:
    instances:
      movie-service:
        maxAttempts: 3
        waitDuration: 1s
