server:
  port: 8080
spring:
  cloud:
    gateway:
      default-filters:
        - name: LogFilter
      routes:
        - id: specieRoute
          uri: lb://SPECIE-SERVICE
          predicates:
            - Path=/specie/**
        - id: animalRoute
          uri: lb://ANIMAL-SERVICE
          predicates:
            - Path=/animal/**
        - id: subscriptionRoute
          uri: lb://SUBSCRIPTION-SERVICE
          predicates:
            - Path=/subscription/**
        - id: movieRoute
          uri: lb://MOVIE-SERVICE
          predicates:
            - Path=/movies/**
        - id: courseRoute
          uri: lb://COURSE-SERVICE
          predicates:
            - Path=/course/**
        - id: catalogRoute
          uri: lb://CATALOG-SERVICE
          predicates:
            - Path=/catalog/**
          filters:
            - AddRequestHeader=course-request-header, custom-course-request-header
            - AddResponseHeader=course-response-header, custom-course-response-header
